#!/usr/bin/env node
// Bundles the browser extension for Chrome/Arc and Firefox.
// - Reads builtin-rules.json + builtin-packs/*.json at build time and emits
//   src/rules.generated.ts so the bundled content script has no fs dependency.
// - Bundles content.ts, action.ts, options.ts as three separate IIFE bundles.
// - Copies manifest, HTML, CSS, and icon into extension-browser-dist/.
// - Optionally zips the dist directory for store submissions.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { build, context } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const distDir = join(repoRoot, 'extension-browser-dist');
const srcDir = join(here, 'src');
const watch = process.argv.includes('--watch');
const doZip = process.argv.includes('--zip');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function generateRulesModule() {
  const builtin = readJson(join(repoRoot, 'builtin-rules.json'));
  const packsDir = join(repoRoot, 'builtin-packs');
  const packEntries = readdirSync(packsDir)
    .filter(f => f.endsWith('.json'))
    .map(f => [f.replace(/\.json$/, ''), readJson(join(packsDir, f))]);

  const lines = [
    '// AUTO-GENERATED by extension-browser/build.mjs -- do not edit by hand.',
    "import type { RawList } from '../../src/core/rules';",
    '',
    `export const BUILTIN_RAW: RawList = ${JSON.stringify(builtin)};`,
    '',
    'export const PACK_RAWS: Record<string, RawList> = {',
    ...packEntries.map(([name, raw]) => `  ${JSON.stringify(name)}: ${JSON.stringify(raw)},`),
    '};',
    '',
    `export const PACK_NAMES: readonly string[] = ${JSON.stringify(packEntries.map(([n]) => n))};`,
    '',
  ];

  writeFileSync(join(srcDir, 'rules.generated.ts'), lines.join('\n'), 'utf8');
  console.log(`[ext] generated rules.generated.ts (1 built-in + ${packEntries.length} packs)`);
}

function copyStatic() {
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
  // Manifest
  copyFileSync(join(here, 'manifest.json'), join(distDir, 'manifest.json'));
  // HTML pages and per-page CSS
  for (const f of ['action.html', 'options.html', 'popup.css', 'options.css']) {
    copyFileSync(join(srcDir, f), join(distDir, f));
  }
  // Icons at 16/32/48/128 for toolbar and store listings.
  const iconsSrc = join(here, 'icons');
  const iconsDist = join(distDir, 'icons');
  if (existsSync(iconsSrc)) {
    if (!existsSync(iconsDist)) mkdirSync(iconsDist, { recursive: true });
    for (const f of readdirSync(iconsSrc)) {
      if (f.endsWith('.png')) copyFileSync(join(iconsSrc, f), join(iconsDist, f));
    }
  }
}

async function run() {
  if (existsSync(distDir)) rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });
  generateRulesModule();
  copyStatic();

  const commonOpts = {
    bundle: true,
    minify: !watch,
    sourcemap: watch ? 'inline' : false,
    format: 'iife',
    platform: 'browser',
    target: ['chrome110', 'firefox128'],
    logLevel: 'info',
  };

  const entries = [
    { entryPoints: [join(srcDir, 'content.ts')], outfile: join(distDir, 'content.js'), ...commonOpts },
    { entryPoints: [join(srcDir, 'action.ts')],  outfile: join(distDir, 'action.js'),  ...commonOpts },
    { entryPoints: [join(srcDir, 'options.ts')], outfile: join(distDir, 'options.js'), ...commonOpts },
  ];

  if (watch) {
    const ctxs = await Promise.all(entries.map(e => context(e)));
    await Promise.all(ctxs.map(c => c.watch()));
    console.log('[ext] watching extension-browser/ for changes...');
    return;
  }

  await Promise.all(entries.map(e => build(e)));
  console.log(`[ext] wrote ${distDir}/{content,action,options}.js`);

  if (doZip) {
    const version = readJson(join(here, 'manifest.json')).version;
    const zipName = `llm-slop-detector-browser-${version}.zip`;
    const zipPath = join(repoRoot, zipName);
    if (existsSync(zipPath)) rmSync(zipPath);
    // -j would flatten; we need the dist layout intact but without the dist dir prefix.
    execSync(`cd "${distDir}" && zip -r -9 "${zipPath}" .`, { stdio: 'inherit' });
    console.log(`[ext] wrote ${zipName}`);
  }
}

run().catch(e => {
  console.error(e);
  process.exit(1);
});
