#!/usr/bin/env node
// Bundles the web playground for GitHub Pages.
// - Reads builtin-rules.json and builtin-packs/*.json at build time and emits
//   web/rules.generated.ts so the browser bundle has no fs dependency.
// - Bundles web/main.ts -> web-dist/main.js via esbuild.
// - Copies web/index.html and web/style.css into web-dist/.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, context } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const distDir = join(repoRoot, 'web-dist');
const watch = process.argv.includes('--watch');

function readJson(path) {
  const text = readFileSync(path, 'utf8');
  return JSON.parse(text);
}

function generateRulesModule() {
  const builtin = readJson(join(repoRoot, 'builtin-rules.json'));
  const packsDir = join(repoRoot, 'builtin-packs');
  const packEntries = readdirSync(packsDir)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      const name = f.replace(/\.json$/, '');
      return [name, readJson(join(packsDir, f))];
    });

  const lines = [
    '// AUTO-GENERATED by web/build.mjs -- do not edit by hand.',
    "import type { RawList } from '../src/core/rules';",
    '',
    `export const BUILTIN_RAW: RawList = ${JSON.stringify(builtin)};`,
    '',
    'export const PACK_RAWS: Record<string, RawList> = {',
    ...packEntries.map(([name, raw]) => `  ${JSON.stringify(name)}: ${JSON.stringify(raw)},`),
    '};',
    '',
    `export const PACK_NAMES: readonly string[] = ${JSON.stringify(packEntries.map(([n]) => n))};`,
    '',
  ];

  writeFileSync(join(here, 'rules.generated.ts'), lines.join('\n'), 'utf8');
  console.log(`[web] generated rules.generated.ts (1 built-in + ${packEntries.length} packs)`);
}

function copyStatic() {
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
  // Copy every static .html / .css file in web/. Currently index.html,
  // privacy.html, and style.css -- automatic so we don't have to update
  // this list when new pages are added.
  for (const f of readdirSync(here)) {
    if (f.endsWith('.html') || f.endsWith('.css')) {
      copyFileSync(join(here, f), join(distDir, f));
    }
  }
}

async function run() {
  if (existsSync(distDir)) rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });
  generateRulesModule();
  copyStatic();

  const esbuildOpts = {
    entryPoints: [join(here, 'main.ts')],
    outfile: join(distDir, 'main.js'),
    bundle: true,
    minify: !watch,
    sourcemap: watch ? 'inline' : false,
    format: 'iife',
    platform: 'browser',
    target: ['es2022'],
    logLevel: 'info',
  };

  if (watch) {
    const ctx = await context(esbuildOpts);
    await ctx.watch();
    console.log('[web] watching web/ for changes...');
  } else {
    await build(esbuildOpts);
    console.log(`[web] wrote ${distDir}/main.js`);
  }
}

run().catch(e => {
  console.error(e);
  process.exit(1);
});
